apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: connect
  name: ingress-resource
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: connect.example.com
    http:
      paths:
      - backend:
          serviceName: onepassword-connect
          servicePort: 8080
        path: /
  tls:
  - hosts:
    - connect.example.com
    secretName: connect-cert