apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: connect
  name: ingress-resource
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: connect.example.com
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: onepassword-connect
            port:
              number: 8080
  tls:
  - hosts:
    - connect.example.com
    secretName: connect-cert
